### ISSUE TITLE
How to create automation

### ISSUE THREAD

**Issue by Draghmar** [HBDK/Eco2-Tools#6]
Hi
I'm not sure if that is actually question for you. If not just point me to the proper channel. :P

I was trying to replace build-in schedule in Eco2 with very simple automation in Hassio. I set Eco2 to manual mode and created something like this (mostly for testing):
```yaml
- id: '1606402829689'
  alias: VRT Sypialnia Off
  description: ''
  trigger:
  - platform: time
    at: '07:10'
  condition: []
  action:
  - condition: state
    entity_id: climate.sypialnia_thermostat
    attribute: temperature
    state: 17
  mode: queued
```
But it doesn't work. The automation is of course executed but it doesn't do anything as well as when executed manually. Actually the only way I found it working was by changing target temp from `lovelace` thermostat card, which let me to believe that I did something wrong in the config. 
I've also tried to do something like this for the action part:
```yaml
  action:
  - service: mqtt.publish
    data:
      payload: '{"temperature":22}'
      topic: etrv/DanfossSypialnia/set
```
but being noob here, I'm not even sure if that's the proper approach, not to mention how and what to actually send. And it also didn't work.

Any tips? :)

**Comment by HBDK** [comment]
i assume you found out what was wrong since you closed the issue, but i would really appreciate it if you would post the solution before doing so.

the issue is that you configured it wrong. i can't tell if your trigger is completely right but the action part is definitely not right.

this is how i set temperatures from a automation

```
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.sypialnia_thermostat
      temperature: 17
```

**Comment by Draghmar** [comment]
Actually this worked for me:
```yaml
  action:
  - service: mqtt.publish
    data:
      payload: 22
      topic: etrv/DanfossSypialnia/set
```
I found out that after looking at logs where I noticed info about payload not being proper float and looking at the code where `/set` is tied to temperature only.
And because script executes refresh after setting temp then everything is updated.
